version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    assignees:
      - "celeranis"
    allow:
      - dependency-type: "production"